# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0cdf32aa98efd4f394ef6b79879eb917"
name = "vowelweb-shubham-task"
handle = "vowelweb-shubham-task"
application_url = "https://individually-visitor-phentermine-invitation.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "vowelweb-shubham.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://individually-visitor-phentermine-invitation.trycloudflare.com/auth/callback",
  "https://individually-visitor-phentermine-invitation.trycloudflare.com/auth/shopify/callback",
  "https://individually-visitor-phentermine-invitation.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
